spring:
  # .env import
  config:
    activate:
      on-profile: local
  datasource:
    redis:
      host: localhost
      port: 6379

  jpa:
    # local - create
    # update - dev
    # none - prod
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

