server:
  port: 8080

spring:
  profiles:
    active: local
  # .env import
#  config:
#    import: optional:file:.env[.properties]
  # Using POSTGRESQL
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # local - create
    # update - dev
    # none - local
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        #        show_sql: true
        #        format_sql: true

  springfox:
    documentation:
      swagger:
        use-model-v3: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
