server:
  port: 8081

spring:
  # .env import
  config:
    activate:
      on-profile: dev
  datasource:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    # local - create
    # update - dev
    # none - prod
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false

