server:
  port: 8080

spring:
  servlet:
    multipart:
      #file upload size
      max-file-size: 10MB

  profiles:
    active: local
  # Using POSTGRESQL
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # local - create
    # update - dev
    # none - local
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        #        show_sql: true
        #        format_sql: true

  springfox:
    documentation:
      swagger:
        use-model-v3: false

fcm:
  key:
    path: naechinso-fcm.json
    scope: https://www.googleapis.com/auth/cloud-platform

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  com.amazonaws.util.EC2MetadataUtils: error
